# Generated by Django 3.1.4 on 2020-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='floor_number',
            field=models.CharField(max_length=2, verbose_name='Floor #'),
        ),
        migrations.AlterField(
            model_name='place',
            name='room_number',
            field=models.CharField(max_length=5, verbose_name='Room #'),
        ),
    ]
