# Generated by Django 3.1.4 on 2020-12-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201216_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='places.city'),
        ),
    ]
