# Generated by Django 3.1.4 on 2020-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('on hold', 'On Hold'), ('unknown', 'Unknown')], default='unknown', max_length=8),
        ),
    ]
